app1/urls.py
from django.urls import path
from app1 import views


app_name = 'app1'



urlpatterns = [
    path('cousre',views.syllabus,name='syllabus'),
    path('admission',views.admission,name='admission'),
    path('info',views.information,name='info'),
    path('delete/<int:id>',views.delete,name='delete'),
]

prac18/urls.py
from django.contrib import admin
from django.urls import path,include
from app1.views import index



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('app1/',include('app1.urls',namespace='app1')),
]

app1/models.py
from django.db import models

# Create your models here.





class course(models.Model):
    subjects = models.CharField(max_length=50)
    duration = models.CharField(max_length=50)
    fee = models.IntegerField()


class create(models.Model):
    sname = models.CharField(max_length=50)
    subject = models.CharField(max_length=50)
    fee = models.IntegerField()

app1/views.py
from django.shortcuts import render
from app1.models import course,create
from app1.forms import courseForm
from django.http import HttpResponseRedirect

# Create your views here.



def index(request):
    return render(request,'app1/index.html',{'msg':'this is homepage'})




def syllabus(request):
    Course = course.objects.all
    b = {'msg':'Available courses','acer':Course}
    return render(request,'app1/course.html',b)


def admission(request):
    form = courseForm()
    if request.method == 'POST':
        form = courseForm(request.POST)
        if form.is_valid():
            form.save()
            form = courseForm()
        else:
            print('invalid course form data')
    a = {'msg':'insert course date','form':form}
    return render(request,'app1/admission.html',a)



def information(request):
    n = create.objects.all()
    display = {'msg':'this is student information','dell':n}
    return render(request,'app1/info.html',display)




def delete(request,id):
    n = create.objects.get(pk=id)
    n.delete()
    return HttpResponseRedirect('/app1/info')

templates/app1/admission.html
{% extends 'base.html' %}
{% load static %}
{% block b1 %}
 <h1>
    {{msg}}
 </h1>
  {% if form  %}
        <form action="" method="post">
            {% csrf_token %}
            <h3>{{form.as_p}}</h3>
            <input type="submit" value="submit">
        </form>
    {% endif %}
{% endblock b1 %}

templates/app1/course.html
{% extends 'base.html' %}
{% load static %}
{% block b1 %}
 <h1>
    {{msg}}
 </h1>
 {% for i in acer %}
     {{i.subjects}}
     {{i.duration}}
     {{i.fee}}
 {% endfor %}
 {% endblock b1 %}

templates/app1/index.html
{% extends 'base.html' %}
{% load static %}
{% block b1 %}
 <h1>
    {{msg}}
 </h1>
 {% endblock b1 %}

templates/app1/info.html
{% extends 'base.html' %}
{% load static %}
{% block b1 %}
 <h1>
    {{msg}}
 </h1>
    {% for i in dell %}
    {{i.sname}}
    <form action="{% url 'app1:delete' i.id%}" method="post">
            {% csrf_token  %}
            <input type="submit" value="DELETE">
        </form>
    {% endfor %}
{% endblock b1 %}

templates/app1/update.html
{% extends 'base.html' %}
{% load static %}
{% block b1 %}
 <h1>
    {{msg}}
 </h1>
  {% if form  %}
        <form action="" method="post">
            {% csrf_token %}
            <h3>{{form.as_p}}</h3>
            <input type="submit" value="submit">
        </form>
    {% endif %}
{% endblock b1 %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>techspace</title>
</head>
<link rel="stylesheet" href="{% static 'bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'index.css' %}">
<body>
    <div class="header">
        <h1>welcome to tech space</h1>
    </div>
    <div>
        <a href="{% url 'index' %}">HOME</a>
        <a href="{% url 'app1:syllabus' %}">Course</a>
        <a href="{% url 'app1:admission' %}">Admission</a>
        <a href="{% url 'app1:info' %}">Info</a>
    </div>
    <div class="c1">
        {% block b1 %}
        {% endblock b1 %}
    </div>
    <div class="footer">
        <h1>     thanks for visting     </h1> 
    </div>
    <div>
        <script src="{% static 'js/bootstrap.js' %}"></script>
        <script src="{% static 'js/jquery.js' %}"></script>
        <script src="{% static 'js/popper.js' %}"></script>
    </div>
</body>
</html>